### ISSUE TITLE
Setup failed for forked-daapd: No setup function defined.

### ISSUE THREAD

**Issue by nicx** [johnpdowling/custom_components#1]
Hi @johnpdowling, I tried your custom component (which I was waiting/looking for months now). Great idea btw! :)

I added it to my Home Assistant configuration with "forked-daapd:" only, then I get this error on start:

`Setup failed for forked-daapd: No setup function defined.`

What can I do? How is this component correctly configured in my configuration.yaml?

**Comment by nicx** [comment]
hey @johnpdowling any chance to get an answer? would be great :)

**Comment by johnpdowling** [comment]
Hi @nicx,

It's configured just like itunes in configuration.yaml, only the optional port defaults to 3689.
```
media_player:
  - platform: forked-daapd
    host: !secret forked-daapd-ip
    port: 3689
```
Hope this helps!
